---
- name: get the API token from an environment variable
  set_fact:
    gdoi_token: "{{ lookup('ENV', 'DO_TOKEN') }}"
  when: gdoi_token is not defined

- name: assert that there is an API token
  assert:
    that: gdoi_token is defined 

- name: call the DO api and get all droplet information
  uri:
    url: "{{ gdoi_api_url }}"
    follow_redirects: all # not required. choices: all;none;safe. Whether or not the URI module should follow redirects. C(all) will follow all redirects. C(safe) will follow only "safe" redirects, where "safe" means that the client is only doing a GET or HEAD on the URI to which it is being redirected. C(none) will not follow any redirects. Note that C(yes) and C(no) choices are accepted for backwards compatibility, where C(yes) is the equivalent of C(all) and C(no) is the equivalent of C(safe). C(yes) and C(no) are deprecated and will be removed in some future version of Ansible.
    headers: 
      Authorization: Bearer {{ gdoi_token }}
    validate_certs: yes # not required. If C(no), SSL certificates will not be validated.  This should only set to C(no) used on personally controlled sites using self-signed certificates.  Prior to 1.9.2 the code defaulted to C(no).
  register: gdoi_return_data

- name: print the list of droplets
  debug:
    msg: "{{ gdoi_return_data.json | json_query('droplets[*].name') }}"
  
- name: add hosts to the group {{ gdoi_default_group }}
  add_host:
      name: "{{ item }}"
      groups: "{{ gdoi_target_group }}" # not required. The groups to add the hostname to, comma separated.
  loop: "{{ gdoi_return_data.json | json_query('droplets[*].name') }}"

- debug:
    var: groups
    #msg: "{{ gdoi_return_data }}"
# - name: parse the result and set a fact as a return object

